# Generated by Django 4.2.3 on 2023-07-13 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_beverages_price_remove_services_price"),
    ]

    operations = [
        migrations.RenameModel(old_name="beverages", new_name="beverage",),
        migrations.RenameModel(old_name="services", new_name="supplie",),
    ]
