# Generated by Django 4.2.3 on 2023-07-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_rename_beverages_beverage_rename_services_supplie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beverage", name="amount", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="supplie", name="amount", field=models.IntegerField(null=True),
        ),
    ]
